name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1- Checkout the main branch from Github
      uses: actions/checkout@v2
    
    - name: Step -2 Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Step - 3 Have github actions build Maven Project
      run: mvn -B package --file pom.xml
    
    - name: Step 4 - List Current directory
      run: |
        cd target
        ls -a 
    
